<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<script>
require(['jquery', 'fastcheckout'],function($, fastcheckout){
    
});
</script>

<?php if ($block->isPossibleOnepageCheckout()){?>
<?php if(!$block->isDisabled()){ ?>
    <button type="button"
            data-role="proceed-to-fastcheckout"
            title="<?php /* @escapeNotVerified */ echo __('Proceed to FastCheckout') ?>"
            data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?php /* @escapeNotVerified */ echo $block->getCheckoutUrl(); ?>"}}'
            class="fastcheckout-button<?php echo($block->isDisabled()) ? ' disabled' : ''; ?>"
            <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
        <img src="https://www.multisafepay.com/downloads/betaalbutton/fco/koop-met-fastcheckout-oranje-large.png"/>
    </button>
    <?php } ?>
<?php }?>

